<h3> 1. ﻿naver finance에서 코스피 200의 리스트를 받아라</h3>

In [ ]:
!pip install pandas-ta

In [41]:
from bs4 import BeautifulSoup
import requests as rq
from datetime import datetime                # 객체를 date 타입으로 만들어줄 모듈
import pandas as pd
# import selenium
# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.by import By
import time
import urllib
import re
import lxml
import pandas_ta as pta

In [2]:
jongmoks = [] #코스피200의 종목이름
codes = [] #코스피200의 종목코드
for page in range(1,21):
    url = f'https://finance.naver.com/sise/entryJongmok.nhn?&page={page}'
    html = rq.get(url)
    soup = BeautifulSoup(html.content, 'html.parser')
    items = soup.find_all('td', {'class': 'ctg'})
    for item in items:
        #print(item)
        txt = item.a.get('href') 
        k = re.search('[\d]+', txt) ##정규표현식 사용. [\d] 숫자표현, + : 반복
        if k:
            code = k.group()
            codes.append(code)
            name = item.text
            jongmoks.append(name)
data = dict(zip(codes, jongmoks)) #코드와 종목이름 결합한 딕셔너리

<h3> 2. 2022년 코스피 200의 1월 ~3월까지의 주가를 모두 받아라﻿ </h3>

In [24]:
for code in data.keys():
    df = None
    dic1 = {'date':[],
       'price':[]}
    for page in range(17, 23):
        req = rq.get(f'https://finance.naver.com/item/sise_day.naver?code={code}&page={page}', headers={'User-Agent':'Mozilla/5.0'})
        html = BeautifulSoup(req.text, 'html.parser')
        lines = html.find_all('tr', {'onmouseover':'mouseOver(this)'})
        for line in lines:
            date = line.find_all('td', {'align': 'center'})[0]
            price = line.find_all('td', {'class': 'num'})[0]
            date_ = date.text.strip()
            if date_ == "":
                break
#             print(date_)
            price_ = price.text.strip()
            dic1['date'].append(date_)
            dic1['price'].append(price_)
    
    df = pd.DataFrame(dic1)
#     print(df['date'])
    df.loc[:,'date'] = pd.to_datetime(df.loc[:,'date'], errors = 'coerce')
    df.loc[:,'price'] = df.loc[:,'price'].str.replace(",","")
#     print(df['price'])
    df.loc[:,'price'] = pd.to_numeric(df.loc[:,'price'])
    df1 = df[(df.loc[:,'date'] >= '2022-01-01') & (df.loc[:,'date'] <= '2022-03-31')]
    df2 = df1.sort_values(by='date')
    globals()['df_{}'.format(code)] = df2.reset_index(drop = True)

<h3> 3. 그들을 DataFrame화 하여 각각에 대해 기술적 분석, MA, MACD, RSI를 구하라 </h3>

In [44]:
for code in codes:
    # 1월부터 3월까지 공휴일이 아닌 일 수는 58일이기 때문에 5일, 20일에 대한 이동평균만 구한다.
    #단순이동평균 SMA
    globals()['df_{}'.format(code)]['sma5'] = globals()['df_{}'.format(code)]['price'].rolling(window=5).mean()
    globals()['df_{}'.format(code)]['sma20'] = globals()['df_{}'.format(code)]['price'].rolling(window=20).mean()
    
    #지수이동평균 EMA
    globals()['df_{}'.format(code)]['ema5'] = globals()['df_{}'.format(code)]['price'].ewm(5).mean()
    globals()['df_{}'.format(code)]['ema20'] = globals()['df_{}'.format(code)]['price'].ewm(20).mean()
    
    #MACD, MACD Signal
    exp1 = globals()['df_{}'.format(code)]['price'].ewm(span=12, adjust=False).mean()
    exp2 = globals()['df_{}'.format(code)]['price'].ewm(span=26, adjust=False).mean()
    globals()['df_{}'.format(code)]['MACD'] = exp1 - exp2
    globals()['df_{}'.format(code)]['Signal line'] = globals()['df_{}'.format(code)]['MACD'].ewm(span=9, adjust=False).mean()
    globals()['df_{}'.format(code)]['rsi14'] = pta.rsi(globals()['df_{}'.format(code)]['price'], length = 14)

In [47]:
df_051910

,date,price,sma5,sma20,ema5,ema20,MACD,Signal line,rsi14
0,2022-01-03,618000,NaN,NaN,618000.000000,618000.000000,0.000000,0.000000,NaN
1,2022-01-04,644000,NaN,NaN,632181.818182,631317.073171,2074.074074,414.814815,NaN
2,2022-01-05,664000,NaN,NaN,644769.230769,642747.026170,5270.866308,1386.025113,NaN
3,2022-01-06,690000,NaN,NaN,659329.359165,655438.357356,9789.482829,3066.716657,NaN
4,2022-01-07,719000,667000.0,NaN,675956.568480,669420.393145,15531.538704,5559.681066,NaN
5,2022-01-10,710000,685400.0,NaN,684487.448036,677034.575430,19135.354120,8274.815677,NaN
6,2022-01-11,734000,703400.0,NaN,695934.086844,686410.531937,23655.319427,11350.916427,NaN
7,2022-01-12,773000,725200.0,NaN,712670.839440,699169.845784,30038.137608,15088.360663,NaN
8,2022-01-13,755000,738200.0,NaN,721421.668910,706650.558986,33260.708689,18722.830268,NaN
9,2022-01-14,716000,737600.0,NaN,720344.009397,707803.697447,32295.364566,21437.337128,NaN
10,2022-01-17,707000,737000.0,NaN,717774.133397,707711.548643,30453.053761,23240.480455,NaN
11,2022-01-18,694000,729000.0,NaN,713311.233959,706238.204740,27625.567476,24117.497859,NaN
12,2022-01-19,653000,705000.0,NaN,702223.013541,700840.572529,21824.823891,23658.963065,NaN
13,2022-01-20,696000,693200.0,NaN,701098.239858,700374.845052,20461.565254,23019.483503,NaN
14,2022-01-21,694000,688800.0,NaN,699833.084368,699789.923951,19000.760735,22215.738949,55.138536
15,2022-01-24,671000,681600.0,NaN,694752.787768,697259.977633,15804.965049,20933.584169,49.499204
16,2022-01-25,643000,671400.0,NaN,685720.194876,692676.345780,10887.404725,18924.348281,43.646736
17,2022-01-26,664000,673600.0,NaN,681958.883647,690340.009540,8585.755985,16856.629821,48.559150
18,2022-01-27,610000,656400.0,NaN,669578.210610,684008.833423,2376.934253,13960.690708,39.116480
19,2022-01-28,639000,645400.0,684700.0,664345.347905,680569.190337,-201.224473,11128.307672,45.271458
20,2022-02-03,677000,646600.0,687650.0,666501.320338,680304.063716,812.482786,9065.142695,52.104193
21,2022-02-04,678000,653600.0,689350.0,668453.121734,680137.358104,1677.210892,7587.556334,52.273060
22,2022-02-07,639000,648600.0,688100.0,663469.033609,677232.793350,-775.520203,5914.941027,45.530842
23,2022-02-08,617000,650000.0,684450.0,655625.530343,673075.531646,-4443.323538,3843.288114,42.222491
24,2022-02-09,610000,644200.0,679000.0,647940.718508,668813.280250,-7824.727021,1509.685087,41.196771
25,2022-02-10,661000,641000.0,676550.0,650136.446195,668295.636886,-6316.428019,-55.537534,50.610772
26,2022-02-11,633000,632000.0,671500.0,647259.428346,666000.013373,-7296.348423,-1503.699712,46.234431
27,2022-02-14,619000,628000.0,663800.0,642520.777463,662995.480204,-9097.752177,-3022.510205,44.177481
28,2022-02-15,622000,629000.0,657150.0,639083.270379,660416.844398,-10166.114068,-4451.230978,44.744776
29,2022-02-16,653000,637600.0,654000.0,641412.537868,659957.343091,-8414.362113,-5243.857205,50.358722
30,2022-02-17,640000,633400.0,650650.0,641176.285502,658738.384301,-7983.053748,-5791.696513,48.149434
31,2022-02-18,629000,632600.0,647400.0,639140.950212,656946.139142,-8431.651994,-6319.687610,46.298550
32,2022-02-21,616000,632000.0,645550.0,635274.699579,654509.257212,-9724.067692,-7000.563626,44.139083
33,2022-02-22,590000,625600.0,640250.0,627713.555115,650715.163961,-12699.902581,-8140.431417,40.109661
34,2022-02-23,589000,612800.0,635000.0,621250.353743,647125.592127,-14966.440997,-9505.633333,39.958569
35,2022-02-24,549000,594600.0,628900.0,609191.615272,641477.814137,-19762.544418,-11557.015550,34.379784
36,2022-02-25,554000,579600.0,624450.0,599982.185265,636492.428975,-22896.100722,-13824.832584,35.590314
37,2022-02-28,565000,569400.0,619500.0,594146.103187,632455.882811,-24212.749101,-15902.415888,38.287545
38,2022-03-02,555000,562400.0,616750.0,587616.421475,628120.962959,-25766.103254,-17875.153361,36.779665
39,2022-03-03,558000,556200.0,612700.0,582676.990550,624229.038406,-26450.171570,-19590.157003,37.573959
40,2022-03-04,535000,553400.0,605600.0,574726.317574,619315.297887,-28519.453909,-21376.016384,34.042627
41,2022-03-07,514000,545400.0,597400.0,564600.480342,613558.591881,-31490.892163,-23398.991540,31.162814
42,2022-03-08,503000,533000.0,590600.0,554329.689627,607557.541770,-34337.564390,-25586.706110,29.743460
43,2022-03-10,496500,521300.0,584575.0,544688.244526,601569.292613,-36695.070386,-27808.378965,28.905656
44,2022-03-11,472000,504100.0,577675.0,532570.223692,594626.632460,-40078.357757,-30262.374723,25.939771
45,2022-03-14,457000,488500.0,567475.0,519972.315886,587295.955960,-43468.929256,-32903.685630,24.296089
46,2022-03-15,439000,473500.0,557775.0,506474.366902,579441.324940,-47065.884940,-35736.125492,22.457131
47,2022-03-16,442000,461300.0,548925.0,495726.938475,572200.335995,-49108.333013,-38410.566996,23.496454
48,2022-03-17,470000,456000.0,541325.0,491438.549921,566843.126238,-47915.284260,-40311.510449,32.579325
49,2022-03-18,488500,459300.0,533100.0,490948.737778,562756.096997,-44958.732853,-41240.954930,37.831178
50,2022-03-21,490000,465900.0,525600.0,490790.600334,558977.722536,-42010.338071,-41394.831558,38.251181
51,2022-03-22,492000,476500.0,518750.0,490992.182328,555514.368511,-39062.047708,-40928.274788,38.844433
52,2022-03-23,508000,489700.0,513350.0,493826.998874,553067.453796,-35030.628789,-39748.745588,43.519459
53,2022-03-24,531000,501900.0,510400.0,500022.827393,551935.406509,-29638.142414,-37726.624953,49.496202
54,2022-03-25,526000,509400.0,507250.0,504352.547362,550609.814199,-25474.363716,-35276.172706,48.299637
55,2022-03-28,523000,516000.0,505950.0,507460.570511,549203.551758,-22161.154038,-32653.168972,47.556767
56,2022-03-29,523000,522200.0,504400.0,510050.554853,547873.323961,-19312.785726,-29985.092323,47.556767
57,2022-03-30,525000,525600.0,502400.0,512542.192719,546715.797471,-16701.525246,-27328.378908,48.173081
58,2022-03-31,532000,525800.0,501250.0,515785.229665,545973.308179,-13906.930564,-24644.089239,50.371434

<h3> 4. 이들을 csv로 만들어서 코드와 csv 200개를 알집으로 제출해라</h3>